grayhatorg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include("posts.urls", namespace='posts')),
    url(r'^$', include("posts.urls", namespace='posts')),
    url(r'^api/', include("posts.api.urls", namespace='posts-api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from .views import (
    PostListAPIView, PostUpdateAPIView,
    PostDetailAPIView, PostDeleteAPIView,
    PostCreateAPIView)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^(?P<slug>[\w-]+)/delete$', PostDeleteAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from .views import (post_delete, post_create,
                    post_details, post_list,
                    post_update)

urlpatterns = [
    url(r'^$', post_list, name="list"),
    url(r'^create$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_details, name="details"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete$', post_delete),

]

posts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.utils.text import slugify
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe

# Create your models here.
def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


class Category(models.Model):
    category_name = models.CharField(max_length=60, default="blog")
    category_description = models.TextField()

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name


class Tag(models.Model):
    tag_name = models.CharField(max_length=50,null="true")
    tag_description = models.TextField()

    def __str__(self):
        return self.tag_name

class Post(models.Model):
    title = models.CharField(max_length=120)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True, blank=True,
                              height_field="height_field",
                              width_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    total_views = models.IntegerField(default=0)
    categories = models.ManyToManyField(Category)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:details", kwargs={"slug": self.slug})
        # return "/post/%s" % self.id

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    class Meta:
        ordering = ["-created", "-updated"]
    objects = PostManager()


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_post_signal_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_post_signal_receiver, sender=Post)

posts/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import Post

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'draft', 'publish', 'categories', 'tags']

posts/api/views.py
from django.db.models import Q

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter
    )
from rest_framework.generics import (
    ListAPIView, RetrieveAPIView,
    UpdateAPIView, DestroyAPIView,
    CreateAPIView,
    RetrieveUpdateAPIView,
    )

from .serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateUpdateSerializer,
    )

from .pagination import PostPageNumberPagination
from posts.models import Post
from rest_framework.permissions import (
    IsAdminUser, AllowAny,
    IsAuthenticatedOrReadOnly,
    IsAuthenticated,
    )

from .permissions import IsOwnerOrReadOnly

class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    lookup_field = 'slug'
    permission_classes = [IsAdminUser, IsOwnerOrReadOnly]

class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'

class PostListAPIView(ListAPIView):
    # queryset = Post.objects.all()
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter]
    SearchFields = ['title', 'content', 'author__first_name', 'author__last_name']
    pagination_class = PostPageNumberPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.active()
        if self.request.user.is_staff or self.request.user.is_superuser:
            queryset_list = Post.objects.all()

        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(author__first_name__icontains=query) |
                Q(author__last_name__icontains=query)
            )
        return queryset_list



class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'

    def perform_update(self, serializer):
        serializer.save(author=self.request.user)

    permission_classes = [IsOwnerOrReadOnly]

class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    lookup_field = 'slug'

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

    permission_classes = [IsAuthenticated, IsAdminUser]

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
# from django.http import HttpResponse
from .models import Post
from .forms import PostForm
from django.utils import timezone
from django.db.models import Q
import logging
# Create your views here.
logger = logging.getLogger(__name__)

def post_create(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        messages.success(request, "post created")
        instance.save()
        form.save_m2m()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Create Post",
        "form": form,
    }
    return render(request, "post_form.html", context)


def post_details(request, slug):
    today = timezone.now().date()
    queryset_top_list = Post.objects.active().order_by('-total_views')[:5]
    instance = get_object_or_404(Post, slug=slug)
    print(instance.slug)
    if instance.draft:
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    if not instance.draft:
        instance.total_views += 1
        instance.save()
    context = {
        "title": instance.title,
        "instance": instance,
        "today": today,
        "top_post": queryset_top_list,
    }
    return render(request, "post_details.html", context)


def post_list(request):
    queryset_list = Post.objects.active()
    queryset_top_list = Post.objects.active().order_by('-total_views')[:9]
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query) |
            Q(author__last_name__icontains=query)
        )

    paginator = Paginator(queryset_list, 8) #shows 8 posts per page
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # if page number is not an integer deliver the first page
        queryset = paginator.page(1)
    except EmptyPage:
        # if page is out of range (e.g 9999) deliver the last page
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "page_request_var": page_request_var,
        "top_post": queryset_top_list,
    }
    return render(request, 'post_list.html', context)


def post_update(request, slug):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None,request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        messages.success(request, "Post updated")
        instance.save()
        form.save_m2m()
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "title": "Edit Post",
        "form": form
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, "Post deleted")
    return redirect("posts:list")

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block head_title %}gray-hat{% endblock head_title %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href='{% static "css/base.css" %}' >
    <style>
        {% block style %}{% endblock style %}
    </style>
{% block extra_head %} {% endblock extra_head %}
</head>
<body class="bd-docs" data-spy="scroll" data-target=".bd-sidenav-active" style="background-color: #e9eaed">
{% include "messages.html" %}
  <nav class="navbar navbar-toggleable-md navbar-inverse navbar-fixed-top bg-faded" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggler-left" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "posts:list" %}">GrayHat</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url "posts:list" %}">Home</a>
                    </li>
{#                    <li>#}
{#                        <a href="#">Pentesting</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">Python</a>#}
{#                    </li>#}
{#                    <li>#}
{#                        <a href="#">Shell Scripting</a>#}
{#                    </li>#}
                </ul>
{#                <ul class="nav navbar-nav navbar-right">#}
{#                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>#}
{#                    <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>#}
{#                </ul>#}
{#                <form  class="navbar-form" " role="search" method="GET" action="">#}
{#                    <div class="input-group">#}
{#                    <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}">#}
{#                    <span class="input-group-btn">#}
{#                        <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="Search">#}
{#                    </span>#}
{#                    </div>#}
{#                </form>#}
{#                <form class="navbar-form navbar-right">#}
{#                    <div class="input-group">#}
{#                        <input type="text" class="form-control" placeholder="Search">#}
{#                        <div class="input-group-btn">#}
{#                            <button class="btn btn-default" type="submit">#}
{#                                <i class="glyphicon glyphicon-search">!</i>#}
{#                            </button>#}
{#                        </div>#}
{#                    </div>#}
{#                </form>#}
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<div class="container" style="margin-top:60px;" >
        {% block content %}{% endblock content %}
</div>
{#<img src="{% static 'img/beach.jpg' %}">#}
<!-- Latest compiled and minified JavaScript -->
<script
			  src="https://code.jquery.com/jquery-1.12.4.min.js"
			  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
			  crossorigin="anonymous">

</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js" > </script>

<script type="text/javascript">
    $(document).ready(function () {
        $(".content-markdown").each(function () {
            var content = $(this).text()
{#            console.log(content)#}
            var markedContent = marked(content)
{#            console.log(markedContent)#}
            $(this).html(markedContent)
        })
        $(".post-detail-item img").each(function () {
           $(this).addClass("img-responsive")
        })

        var titleItem = $("#id_title");
        function setTitle(value) {
            $("#preview-title").text(value)
        }
        setTitle(titleItem.val())

        var contentItem = $("#id_content");
        function setContent(value) {
            var markedContent = marked(value)
            $("#preview-content").html(markedContent)
            $("#preview-content img").each(function () {
                $(this).addClass("img-responsive")
            })
        }
        setContent(contentItem.val())

        titleItem.keyup(function () {
            var newVal = $(this).val()
            setTitle(newVal)
        })

        contentItem.keyup(function () {
            var newContent = $(this).val()
            setContent(newContent)
        })
    })
</script>

</body>
</html>

templates/messages.html
{% if messages %}
    <div class="messages"
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    </div>
{% endif %}

templates/post_details.html
{% extends "base.html" %}

{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <div class="col-sm-8">
    <div class="thumbnail">
    {% if instance.image %}
    <img src="{{ instance.image.url }}" class="img-responsive">
    {% endif %}
        <div class="caption">
        <h2>{{ instance.title }} <small>{{ instance.publish }}</small></h2>
            {% if instance.draft %} <span style="color: red;">Draft : staff only</span>{% endif %}<br>
            {% if instance.publish > today %} <span style="color: red;">Future post : staff only</span> <br>{% endif %}
{#            <div class="col-sm-2"><span class=" glyphicon glyphicon-eye-open"></span> {{ instance.total_views }}#}
{#            </div>#}
            <div class="col-sm-4"> <span class="glyphicon glyphicon-user"></span> {{ instance.author.get_full_name }}
            </div>
            <div class="col-sm-4"><span class="glyphicon glyphicon-folder-open"></span>

                 {% for cat in instance.categories.all|slice:':1' %}
                    {{ cat }}
                {% endfor %}
                {% for cat in instance.categories.all|slice:'1:' %}
                    , {{ cat }}
                {% endfor %}
            </div>
        <br>
            <div class="post-detail-item text-justify" >{{ instance.get_markdown }}</div> </br>
        </div>
    </div>
    {% load disqus_tags %}
    {% disqus_dev %}
    {% set_disqus_identifier 'instance.id' %}
    {% set_disqus_url instance.get_absolute_url %}
    {% set_disqus_title instance.title %}
    {% disqus_show_comments 'grayhat-heroku' %}
    </div>
    <div class="col-sm-4 fixed">
         <form role="search" method="GET" action="/post/">
            <div class="input-group">
                <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit" aria-describedby="btnGroupAddon">Search</button>
                </span>
            </div>
        </form>
        <hr>
            <div class="panel panel-default">
            <div class="panel-heading">
            <h4 class="text-center">TOP POSTS</h4>
            </div>
            <ul class="list-group">
                {% for obj in top_post %}
                <li class="list-group-item"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></li>
                {% endfor %}
            </ul>
            </div>
    </div>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-58d00e78fd9b06eb"></script>

{% endblock content %}

templates/post_form.html
{% extends "base.html" %}
{% block extra_head %}
{{ form.media }}
{% endblock extra_head %}

{% block content %}
    <div class="col-sm-6">
    <div class="content-preview">
    <h1>Preview</h1>
    <h3 id="preview-title"></h3>
    <p id="preview-content"></p>
    </div>
    </div>

    <div class="col-sm-6">
    <h1>Form</h1>
    <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-default" value="Create Post">
    </form>
    </div>
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-8">
{#        <h1> {{ title }}</h1>#}
    {% for obj in object_list %}
        <div class="row">
        <div class="col-sm-12" >
        <div class="thumbnail">
            {% if obj.image %}
            <img src="{{ obj.image.url }}">
            {% endif %}
          <div class="post-detail-item caption" >
              <h2><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> <small><span class="glyphicon glyphicon-calendar"></span>{{ obj.publish|timesince }} ago</small></h2>
{#              <div class="col-sm-2"> <span class=" glyphicon glyphicon-eye-open"></span> {{ obj.total_views }}#}
{#              </div>#}
              <div class="col-sm-4"> <span class="glyphicon glyphicon-user"></span> {{ obj.author.get_full_name }}
              </div>
              <div class="col-sm-4"> <span class="glyphicon glyphicon-folder-open"></span>
                {% for cat in obj.categories.all|slice:':1' %}
                    {{ cat }}
                {% endfor %}
                {% for cat in obj.categories.all|slice:'1:' %}
                    , {{ cat }}
                {% endfor %}
{#              {% if obj.author.get_full_name %}#}
{#                  <span class="glyphicon glyphicon-user"> {{ obj.author.get_full_name }}</span>#}
{#            {% endif %}#}
              </div>
          <br>
            <p class="text-justify">{{ obj.get_markdown|truncatechars_html:240}}</p>
            <a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">Read More</a>
          </div>
        </div>
        </div>
        </div>
    {% endfor %}

    <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
    </div>
    </div>
    <div class="col-sm-4 fixed">
         <form role="search" method="GET" action="">
            <div class="input-group">
                <input class="form-control" type="text" name="q" placeholder="Search" value="{{ request.GET.q }}">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="submit" aria-describedby="btnGroupAddon">Search</button>
                </span>
            </div>
        </form>
        <hr>
            <div class="panel panel-default">
            <div class="panel-heading">
            <h4 class="text-center">TOP POSTS</h4>
            </div>
            <ul class="list-group">
                {% for obj in top_post %}
                <li class="list-group-item"><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></li>
                {% endfor %}
            </ul>
            </div>
     </div>
{#    search box#}

{% endblock content %}